apiVersion: minio.storage.sealos.io.sealos.io/v1
kind: Minio
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio-sample
  namespace: user-namespace
spec:
  replicas: 4
  clusterVersionRef: minio/minio:RELEASE.2023-06-29T05-12-28Z
  ingressType: nginx
  consolePublic: false
  s3Public: false
  pvcNum: 32
  resoure:
    limits:
      cpu: "1"
      memory: 256Mi
    requests:
      cpu: "1"
      memory: "256Mi"
      storage: 10Gi
