# permissions for end users to view minios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: minio-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: minio
    app.kubernetes.io/part-of: minio
    app.kubernetes.io/managed-by: kustomize
  name: minio-viewer-role
rules:
- apiGroups:
  - minio.storage.sealos.io.sealos.io
  resources:
  - minios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - minio.storage.sealos.io.sealos.io
  resources:
  - minios/status
  verbs:
  - get
